/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Telas.Tela03_B_HomeGerencia;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produtos;
import model.ProdutosDao;

/**
 *
 * @author Denise Trevizo (usp)
 */
public class Tela04_B3_TabbedProdutosGerencia extends javax.swing.JFrame {

    /**
     * Creates new form TabbedClientesGerencia
     */
    public Tela04_B3_TabbedProdutosGerencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        voltarProdutosGerencia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProd = new javax.swing.JTable();
        pesquisaProd = new javax.swing.JTextField();
        btnPesquisarProd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inserirCadProd = new javax.swing.JButton();
        atualizarCadProd = new javax.swing.JButton();
        voltarCadProd = new javax.swing.JButton();
        excluirCadProd = new javax.swing.JButton();
        fornecedorCadProd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        descricaoCadProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nomeCadProd = new javax.swing.JTextField();
        validadeCadProd = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        valorCadProd = new javax.swing.JTextField();
        categoriaCadProd = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        qtdCadProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        codCadProd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(242, 242, 242));
        jTabbedPane1.setForeground(new java.awt.Color(67, 1, 101));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 208, 119));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(67, 1, 101));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Consultar Produtos");
        jLabel2.setOpaque(true);

        voltarProdutosGerencia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarProdutosGerencia.setForeground(new java.awt.Color(204, 0, 0));
        voltarProdutosGerencia.setText("<<");
        voltarProdutosGerencia.setBorderPainted(false);
        voltarProdutosGerencia.setContentAreaFilled(false);
        voltarProdutosGerencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarProdutosGerenciaActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabelaProd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabelaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Produto", "Fornecedor", "Nome", "Descrição", "Validade", "Categoria", "Valor", "Qtd."
            }
        ));
        tabelaProd.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tabelaProd);

        pesquisaProd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnPesquisarProd.setBackground(new java.awt.Color(30, 0, 45));
        btnPesquisarProd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPesquisarProd.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarProd.setText("Pesquisar");
        btnPesquisarProd.setBorderPainted(false);
        btnPesquisarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarProdutosGerencia)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pesquisaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarProd))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 270, Short.MAX_VALUE)
                        .addComponent(voltarProdutosGerencia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pesquisaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta", jPanel3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 208, 119));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 1, 101));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Produtos");
        jLabel1.setOpaque(true);

        inserirCadProd.setBackground(new java.awt.Color(30, 0, 45));
        inserirCadProd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        inserirCadProd.setForeground(new java.awt.Color(255, 255, 255));
        inserirCadProd.setText("Inserir");
        inserirCadProd.setBorderPainted(false);
        inserirCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirCadProdActionPerformed(evt);
            }
        });

        atualizarCadProd.setBackground(new java.awt.Color(30, 0, 45));
        atualizarCadProd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        atualizarCadProd.setForeground(new java.awt.Color(255, 255, 255));
        atualizarCadProd.setText("Atualizar");
        atualizarCadProd.setBorderPainted(false);
        atualizarCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCadProdActionPerformed(evt);
            }
        });

        voltarCadProd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarCadProd.setForeground(new java.awt.Color(204, 0, 0));
        voltarCadProd.setText("<<");
        voltarCadProd.setBorderPainted(false);
        voltarCadProd.setContentAreaFilled(false);
        voltarCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCadProdActionPerformed(evt);
            }
        });

        excluirCadProd.setBackground(new java.awt.Color(30, 0, 45));
        excluirCadProd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        excluirCadProd.setForeground(new java.awt.Color(255, 255, 255));
        excluirCadProd.setText("Excluir");
        excluirCadProd.setBorderPainted(false);
        excluirCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCadProdActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Categoria");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Descrição");

        try {
            validadeCadProd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        validadeCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validadeCadProdActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nome");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Validade");

        categoriaCadProd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        categoriaCadProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentos", "Higiene e Beleza", "Farmácia", "Acessórios" }));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Valor");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Código");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Qtd.");

        codCadProd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                codCadProdMouseMoved(evt);
            }
        });
        codCadProd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codCadProdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GetProduto(evt);
            }
        });
        codCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codCadProdActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Fornecedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(voltarCadProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fornecedorCadProd)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(excluirCadProd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(atualizarCadProd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inserirCadProd))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(codCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(nomeCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(descricaoCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(categoriaCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(valorCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15)
                                    .addGap(72, 72, 72)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(validadeCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(qtdCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))))
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validadeCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(categoriaCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtdCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(voltarCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fornecedorCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atualizarCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inserirCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(excluirCadProd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparCampos(){
        codCadProd.setText("");
        nomeCadProd.setText("");
        descricaoCadProd.setText("");
        validadeCadProd.setText("");
        valorCadProd.setText("");
        qtdCadProd.setText("");
        fornecedorCadProd.setText("");
    }
    
    private void inserirCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirCadProdActionPerformed
        Produtos Produtos = new Produtos();
        ProdutosDao pdao = new ProdutosDao();

        Produtos.setcod_prod(Integer.parseInt(codCadProd.getText()));
        Produtos.setnome(nomeCadProd.getText());
        Produtos.setdescricao(descricaoCadProd.getText());
        Produtos.setdata_validade(validadeCadProd.getText());
        Produtos.setcategoria(String.valueOf(categoriaCadProd.getSelectedItem()));
        Produtos.setvalor(Integer.parseInt(valorCadProd.getText()));
        Produtos.setquantidade(Integer.parseInt(qtdCadProd.getText()));
        Produtos.setcod_for(Integer.parseInt(fornecedorCadProd.getText()));
        
        limparCampos();

        pdao.create(Produtos);    }//GEN-LAST:event_inserirCadProdActionPerformed

    private void voltarProdutosGerenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarProdutosGerenciaActionPerformed
        Tela03_B_HomeGerencia telaHomeGerencia = new Tela03_B_HomeGerencia();
        telaHomeGerencia.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarProdutosGerenciaActionPerformed

    private void atualizarCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCadProdActionPerformed
        Produtos Produtos = new Produtos();
        ProdutosDao pdao = new ProdutosDao();

        Produtos.setcod_prod(Integer.parseInt(codCadProd.getText()));
        Produtos.setnome(nomeCadProd.getText());
        Produtos.setdescricao(descricaoCadProd.getText());
        Produtos.setdata_validade(validadeCadProd.getText());
        Produtos.setcategoria(String.valueOf(categoriaCadProd.getSelectedItem()));
        Produtos.setvalor(Integer.parseInt(valorCadProd.getText()));
        Produtos.setquantidade(Integer.parseInt(qtdCadProd.getText()));
        Produtos.setcod_for(Integer.parseInt(fornecedorCadProd.getText()));

        pdao.update(Produtos);
    }//GEN-LAST:event_atualizarCadProdActionPerformed

    private void voltarCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCadProdActionPerformed
        Tela03_B_HomeGerencia telaHomeGerencia = new Tela03_B_HomeGerencia();
        telaHomeGerencia.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarCadProdActionPerformed

    private void excluirCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCadProdActionPerformed
        Produtos Produtos = new Produtos();
        ProdutosDao pdao = new ProdutosDao();
        Produtos.setcod_prod(Integer.parseInt(codCadProd.getText()));

        pdao.delete(Produtos);

        limparCampos();
    }//GEN-LAST:event_excluirCadProdActionPerformed

    private void btnPesquisarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdActionPerformed
        DefaultTableModel tabelaProdutos = (DefaultTableModel) tabelaProd.getModel();
        tabelaProdutos.setNumRows(0);
        ProdutosDao dao = new ProdutosDao();
        for (Produtos c : dao.getContatos()) {
            tabelaProdutos.addRow(new Object[]{c.getcod_prod(), c.getcod_for(),
                c.getnome(), c.getdescricao(), c.getdata_validade(),
                c.getcategoria(), c.getvalor(), c.getquantidade()
            });
        }
    }//GEN-LAST:event_btnPesquisarProdActionPerformed

    private void codCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codCadProdActionPerformed
     
    }//GEN-LAST:event_codCadProdActionPerformed

    private void validadeCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validadeCadProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validadeCadProdActionPerformed

    private void GetProduto(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GetProduto
        // TODO add your handling code here:
        ProdutosDao Produtos = new ProdutosDao();
        Produtos p = Produtos.getProdutoPorID(Integer.parseInt(codCadProd.getText()));
        
        if (p != null) {
            nomeCadProd.setText(p.getnome());
            descricaoCadProd.setText(p.getdescricao());
            validadeCadProd.setValue(p.getdata_validade());
            //corrigir aqui
            //categoriaCadProd.setEditor(p.getcategoria());  
            valorCadProd.setText(p.getvalor().toString());
            qtdCadProd.setText(p.getquantidade().toString());
            fornecedorCadProd.setText(p.getcod_for().toString());
        } else {
            JOptionPane.showMessageDialog(null, "Produto não encontrado");
            limparCampos();
        }

    }//GEN-LAST:event_GetProduto

    private void pesquisaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaProdActionPerformed

    private void codCadProdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codCadProdMouseMoved
         
    }//GEN-LAST:event_codCadProdMouseMoved

    private void codCadProdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codCadProdFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_codCadProdFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela04_B3_TabbedProdutosGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela04_B3_TabbedProdutosGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela04_B3_TabbedProdutosGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela04_B3_TabbedProdutosGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela04_B3_TabbedProdutosGerencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarCadProd;
    private javax.swing.JButton btnPesquisarProd;
    private javax.swing.JComboBox<String> categoriaCadProd;
    private javax.swing.JTextField codCadProd;
    private javax.swing.JTextField descricaoCadProd;
    private javax.swing.JButton excluirCadProd;
    private javax.swing.JTextField fornecedorCadProd;
    private javax.swing.JButton inserirCadProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nomeCadProd;
    private javax.swing.JTextField pesquisaProd;
    private javax.swing.JTextField qtdCadProd;
    private javax.swing.JTable tabelaProd;
    private javax.swing.JFormattedTextField validadeCadProd;
    private javax.swing.JTextField valorCadProd;
    private javax.swing.JButton voltarCadProd;
    private javax.swing.JButton voltarProdutosGerencia;
    // End of variables declaration//GEN-END:variables
}
