/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Telas.Tela03_B_HomeGerencia;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Produtos;
import model.ProdutosDao;

/**
 *
 * @author Denise Trevizo (usp)
 */
public class Tela04_B5_TabbedCaixaGerencia extends javax.swing.JFrame {

    /**
     * Creates new form TabbedClientesGerencia
     */
    public Tela04_B5_TabbedCaixaGerencia() {
        initComponents();
    }
    
    private void limparCampos(){
        codCaixa.setText("");
        itemCaixa.setText("");
        valorCaixa.setText("");
        qtdCaixa.setText("");
    }
    
    private void limparValores(){
        valorPagCaixa.setText("");
        trocoCaixa.setText("");
        totalPagCaixa.setText("");
        totalCaixa.setText("");
    }

    public void ValorFinal() {
        try {
            double ValorFinal = 0;
            for (int i = 0; i < tabelaCaixa.getRowCount(); i++) {
                ValorFinal += Double.parseDouble(tabelaCaixa.getValueAt(i, 2).toString())
                        * Double.parseDouble(tabelaCaixa.getValueAt(i, 3).toString());
                totalCaixa.setText(String.valueOf(ValorFinal));
            }
        } catch (NumberFormatException e) {
            System.out.println("Erro ao somar: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        voltarProdutosAtendimento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdCaixa = new javax.swing.JTable();
        pesquisaProd1 = new javax.swing.JTextField();
        btnPesquisarProd1 = new javax.swing.JButton();
        avancar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        voltarCaixa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCaixa = new javax.swing.JTable();
        totalCaixa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        finalizarCaixa = new javax.swing.JButton();
        cancelarCaixa = new javax.swing.JButton();
        codCaixa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        itemCaixa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        valorCaixa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adicionarCaixa = new javax.swing.JButton();
        qtdCaixa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        excluirCaixa = new javax.swing.JButton();
        btnLimparCaixa = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaPagCaixa = new javax.swing.JTable();
        totalPagCaixa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        voltarPagamentoCaixa = new javax.swing.JButton();
        dinheiroCaixa = new javax.swing.JButton();
        debitoCaixa = new javax.swing.JButton();
        creditoCaixa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        valorPagCaixa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        trocoCaixa = new javax.swing.JTextField();
        finalizarPagCaixa = new javax.swing.JButton();
        cancelarPagCaixa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(242, 242, 242));
        jTabbedPane1.setForeground(new java.awt.Color(67, 1, 101));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 208, 119));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(67, 1, 101));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Consultar Produtos");
        jLabel2.setOpaque(true);

        voltarProdutosAtendimento.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarProdutosAtendimento.setForeground(new java.awt.Color(204, 0, 0));
        voltarProdutosAtendimento.setText("<<");
        voltarProdutosAtendimento.setBorderPainted(false);
        voltarProdutosAtendimento.setContentAreaFilled(false);
        voltarProdutosAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarProdutosAtendimentoActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabelaProdCaixa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabelaProdCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Produto", "Fornecedor", "Nome", "Descrição", "Validade", "Categoria", "Valor", "Qtd."
            }
        ));
        tabelaProdCaixa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaProdCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdCaixaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdCaixa);

        pesquisaProd1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnPesquisarProd1.setBackground(new java.awt.Color(30, 0, 45));
        btnPesquisarProd1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPesquisarProd1.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisarProd1.setText("Pesquisar");
        btnPesquisarProd1.setBorderPainted(false);
        btnPesquisarProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProd1ActionPerformed(evt);
            }
        });

        avancar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        avancar.setForeground(new java.awt.Color(36, 99, 36));
        avancar.setText(">>");
        avancar.setBorderPainted(false);
        avancar.setContentAreaFilled(false);
        avancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltarProdutosAtendimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pesquisaProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisarProd1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(avancar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(voltarProdutosAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avancar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisarProd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pesquisaProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Consulta", jPanel3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 208, 119));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(67, 1, 101));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Caixa");
        jLabel3.setOpaque(true);

        voltarCaixa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarCaixa.setForeground(new java.awt.Color(204, 0, 0));
        voltarCaixa.setText("<<");
        voltarCaixa.setBorderPainted(false);
        voltarCaixa.setContentAreaFilled(false);
        voltarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarCaixaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(239, 239, 239));

        tabelaCaixa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tabelaCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Cod", "Item.", "Valor", "Qtd."
            }
        ));
        jScrollPane2.setViewportView(tabelaCaixa);

        totalCaixa.setBackground(new java.awt.Color(222, 213, 226));
        totalCaixa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        totalCaixa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCaixaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Total");

        finalizarCaixa.setBackground(new java.awt.Color(30, 0, 45));
        finalizarCaixa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        finalizarCaixa.setForeground(new java.awt.Color(255, 255, 255));
        finalizarCaixa.setText("Finalizar");
        finalizarCaixa.setBorderPainted(false);
        finalizarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarCaixaActionPerformed(evt);
            }
        });

        cancelarCaixa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cancelarCaixa.setForeground(new java.awt.Color(204, 0, 0));
        cancelarCaixa.setText("Cancelar");
        cancelarCaixa.setBorderPainted(false);
        cancelarCaixa.setContentAreaFilled(false);
        cancelarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(cancelarCaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finalizarCaixa))
                    .addComponent(totalCaixa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalizarCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        codCaixa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codCaixaFocusLost(evt);
            }
        });
        codCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codCaixaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Código");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Valor");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Qtd.");

        adicionarCaixa.setBackground(new java.awt.Color(78, 142, 78));
        adicionarCaixa.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        adicionarCaixa.setForeground(new java.awt.Color(255, 255, 255));
        adicionarCaixa.setText("+");
        adicionarCaixa.setBorderPainted(false);
        adicionarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCaixaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Item");

        excluirCaixa.setBackground(new java.awt.Color(183, 77, 77));
        excluirCaixa.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        excluirCaixa.setForeground(new java.awt.Color(255, 255, 255));
        excluirCaixa.setText("-");
        excluirCaixa.setBorderPainted(false);
        excluirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCaixaActionPerformed(evt);
            }
        });

        btnLimparCaixa.setBackground(new java.awt.Color(30, 0, 45));
        btnLimparCaixa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimparCaixa.setForeground(new java.awt.Color(255, 255, 255));
        btnLimparCaixa.setText("Limpar");
        btnLimparCaixa.setBorderPainted(false);
        btnLimparCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(voltarCaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(excluirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adicionarCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qtdCaixa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valorCaixa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(codCaixa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLimparCaixa))
                                    .addComponent(itemCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(codCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(btnLimparCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valorCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtdCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(excluirCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adicionarCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(voltarCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Caixa", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 208, 119));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(67, 1, 101));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pagamento");
        jLabel9.setOpaque(true);

        jPanel5.setBackground(new java.awt.Color(239, 239, 239));

        tabelaPagCaixa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tabelaPagCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Cod", "Item", "Valor", "Qtd."
            }
        ));
        jScrollPane3.setViewportView(tabelaPagCaixa);

        totalPagCaixa.setBackground(new java.awt.Color(222, 213, 226));
        totalPagCaixa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        totalPagCaixa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Total");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(totalPagCaixa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 159, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPagCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        voltarPagamentoCaixa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltarPagamentoCaixa.setForeground(new java.awt.Color(204, 0, 0));
        voltarPagamentoCaixa.setText("<<");
        voltarPagamentoCaixa.setBorderPainted(false);
        voltarPagamentoCaixa.setContentAreaFilled(false);
        voltarPagamentoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarPagamentoCaixaActionPerformed(evt);
            }
        });

        dinheiroCaixa.setBackground(new java.awt.Color(78, 142, 78));
        dinheiroCaixa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dinheiroCaixa.setForeground(new java.awt.Color(255, 255, 255));
        dinheiroCaixa.setText("Dinheiro");
        dinheiroCaixa.setBorderPainted(false);
        dinheiroCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinheiroCaixaActionPerformed(evt);
            }
        });

        debitoCaixa.setBackground(new java.awt.Color(183, 77, 77));
        debitoCaixa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        debitoCaixa.setForeground(new java.awt.Color(255, 255, 255));
        debitoCaixa.setText("Débito");
        debitoCaixa.setBorderPainted(false);
        debitoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitoCaixaActionPerformed(evt);
            }
        });

        creditoCaixa.setBackground(new java.awt.Color(204, 171, 112));
        creditoCaixa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        creditoCaixa.setForeground(new java.awt.Color(255, 255, 255));
        creditoCaixa.setText("Crédito");
        creditoCaixa.setBorderPainted(false);
        creditoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditoCaixaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Forma de pagamento");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Valor pago");

        valorPagCaixa.setBackground(new java.awt.Color(222, 213, 226));
        valorPagCaixa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        valorPagCaixa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        valorPagCaixa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valorPagCaixaFocusLost(evt);
            }
        });
        valorPagCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorPagCaixaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Troco");

        trocoCaixa.setBackground(new java.awt.Color(222, 213, 226));
        trocoCaixa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        trocoCaixa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        trocoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocoCaixaActionPerformed(evt);
            }
        });

        finalizarPagCaixa.setBackground(new java.awt.Color(30, 0, 45));
        finalizarPagCaixa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        finalizarPagCaixa.setForeground(new java.awt.Color(255, 255, 255));
        finalizarPagCaixa.setText("Finalizar");
        finalizarPagCaixa.setBorderPainted(false);
        finalizarPagCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarPagCaixaActionPerformed(evt);
            }
        });

        cancelarPagCaixa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancelarPagCaixa.setForeground(new java.awt.Color(204, 0, 0));
        cancelarPagCaixa.setText("Cancelar");
        cancelarPagCaixa.setBorderPainted(false);
        cancelarPagCaixa.setContentAreaFilled(false);
        cancelarPagCaixa.setOpaque(false);
        cancelarPagCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarPagCaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(voltarPagamentoCaixa)))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dinheiroCaixa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(debitoCaixa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(creditoCaixa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(cancelarPagCaixa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(finalizarPagCaixa))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(45, 45, 45)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(valorPagCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(trocoCaixa)))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltarPagamentoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dinheiroCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(debitoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creditoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(valorPagCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trocoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(finalizarPagCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addComponent(cancelarPagCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                        .addGap(33, 33, 33))))
        );

        jTabbedPane1.addTab("Pagamento", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarProdutosAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarProdutosAtendimentoActionPerformed
        Tela03_B_HomeGerencia telaHomeGerencia = new Tela03_B_HomeGerencia();
        telaHomeGerencia.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarProdutosAtendimentoActionPerformed

    private void voltarPagamentoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarPagamentoCaixaActionPerformed
        Tela03_B_HomeGerencia telaHomeGerencia = new Tela03_B_HomeGerencia();
        telaHomeGerencia.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarPagamentoCaixaActionPerformed

    private void dinheiroCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinheiroCaixaActionPerformed
        JOptionPane.showMessageDialog(null, "Inserir o valor pago.");        
    }//GEN-LAST:event_dinheiroCaixaActionPerformed

    private void debitoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitoCaixaActionPerformed
        valorPagCaixa.setText(String.valueOf(totalPagCaixa.getText()));
        String valorTotal = (String.valueOf(Float.parseFloat(totalPagCaixa.getText()) - Float.parseFloat(valorPagCaixa.getText())));
        trocoCaixa.setText(valorTotal);
    }//GEN-LAST:event_debitoCaixaActionPerformed

    private void creditoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditoCaixaActionPerformed
        valorPagCaixa.setText(String.valueOf(totalPagCaixa.getText()));
        String valorTotal = (String.valueOf(Float.parseFloat(totalPagCaixa.getText()) - Float.parseFloat(valorPagCaixa.getText())));
        trocoCaixa.setText(valorTotal);
    }//GEN-LAST:event_creditoCaixaActionPerformed

    private void finalizarPagCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarPagCaixaActionPerformed
        JOptionPane.showMessageDialog(null, "Compra efetuada.");
        
        //Limpar tabelas de caixa e de pagamento
        tabelaCaixa.setModel(new DefaultTableModel(null, new String[]{"Cod", "Item", "Valor", "Qtd."}));
        tabelaPagCaixa.setModel(new DefaultTableModel(null, new String[]{"Cod", "Item", "Valor", "Qtd."}));
        
        //Limpar campos pesquisados e calculados
        limparCampos();
        limparValores();
        
        //Mudar para a tela de consulta
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_finalizarPagCaixaActionPerformed

    private void btnPesquisarProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProd1ActionPerformed
        DefaultTableModel tabelaProdutos = (DefaultTableModel) tabelaProdCaixa.getModel();
        tabelaProdutos.setNumRows(0);
        ProdutosDao dao = new ProdutosDao();
        for (Produtos c : dao.getContatos(pesquisaProd1.getText().toString())) {
            tabelaProdutos.addRow(new Object[]{c.getcod_prod(), c.getcod_for(),
                c.getnome(), c.getdescricao(), c.getdata_validade(),
                c.getcategoria(), c.getvalor(), c.getquantidade()
            });
        }
    }//GEN-LAST:event_btnPesquisarProd1ActionPerformed

    private void valorPagCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorPagCaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorPagCaixaActionPerformed

    private void trocoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocoCaixaActionPerformed

        try {
            String valorTotal = (String.valueOf(Float.parseFloat(totalPagCaixa.getText()) - Float.parseFloat(valorPagCaixa.getText())));
            trocoCaixa.setText(valorTotal);
        } catch (NumberFormatException ex) {

        }
    }//GEN-LAST:event_trocoCaixaActionPerformed

    private void cancelarCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCaixaActionPerformed
        //Limpar tabela de caixa
        tabelaCaixa.setModel(new DefaultTableModel(null, new String[]{"Cod", "Item", "Valor", "Qtd."}));

        //Limpar campos pesquisados e valores calculados
        limparCampos();
        limparValores();
        
        //Mudar para a tela de consulta
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_cancelarCaixaActionPerformed

    private void finalizarCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarCaixaActionPerformed
        //Passa o valor total para tela de pagamento.
        totalPagCaixa.setText(totalCaixa.getText());

        //Zera a tebla de pagamento. Solucao caso para voltar e incluir ou excluir item.
        DefaultTableModel modelo = (DefaultTableModel) tabelaPagCaixa.getModel();
        modelo.setRowCount(0);

        //Copia a tabela  caixa para tabela pagamento.
        for (int i = 0; i < tabelaCaixa.getRowCount(); i++) {
            modelo.addRow(new Object[]{tabelaCaixa.getValueAt(i, 0).toString(), tabelaCaixa.getValueAt(i, 1).toString(), tabelaCaixa.getValueAt(i, 2).toString(), tabelaCaixa.getValueAt(i, 3).toString()});
        }
        
        //Muda para a tela de pagamento
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_finalizarCaixaActionPerformed

    private void totalCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCaixaActionPerformed

    }//GEN-LAST:event_totalCaixaActionPerformed

    private void voltarCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarCaixaActionPerformed
        Tela03_B_HomeGerencia telaHomeGerencia = new Tela03_B_HomeGerencia();
        telaHomeGerencia.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarCaixaActionPerformed

    private void codCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codCaixaActionPerformed

    }//GEN-LAST:event_codCaixaActionPerformed

    private void codCaixaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codCaixaFocusLost
        ProdutosDao Produtos = new ProdutosDao();
        Produtos p = Produtos.getProdutoPorID(Integer.parseInt(codCaixa.getText()));

        if (p != null) {
            itemCaixa.setText(p.getnome());
            valorCaixa.setText(p.getvalor().toString());
            qtdCaixa.setText("1");

        } else {
            JOptionPane.showMessageDialog(null, "Produto não encontrado");
            //limparCampos();
        }
    }//GEN-LAST:event_codCaixaFocusLost

    private void excluirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCaixaActionPerformed
        int x = tabelaCaixa.getSelectedRow();
        if (x != -1) {
            DefaultTableModel modelo = (DefaultTableModel) tabelaCaixa.getModel();
            modelo.removeRow(x);
        } else {

        }
        ValorFinal();
        if (tabelaCaixa.getRowCount() == 0) {
            totalCaixa.setText("0.0");
        }
    }//GEN-LAST:event_excluirCaixaActionPerformed

    private void adicionarCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCaixaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tabelaCaixa.getModel();
        modelo.addRow(new Object[]{codCaixa.getText(), itemCaixa.getText(), valorCaixa.getText(), qtdCaixa.getText()});
        //int x = tabelaCaixa.get();
        ValorFinal();
    }//GEN-LAST:event_adicionarCaixaActionPerformed

    private void tabelaProdCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdCaixaMouseClicked
        int i = tabelaProdCaixa.getSelectedRow();
        TableModel model = tabelaProdCaixa.getModel();
        codCaixa.setText(model.getValueAt(i, 0).toString());
        itemCaixa.setText(model.getValueAt(i, 2).toString());
        valorCaixa.setText(model.getValueAt(i, 6).toString());
        qtdCaixa.setText("1");
    }//GEN-LAST:event_tabelaProdCaixaMouseClicked

    private void btnLimparCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCaixaActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCaixaActionPerformed

    private void cancelarPagCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarPagCaixaActionPerformed
        //Limpar as tabelas de caixa e de pagamento
        tabelaPagCaixa.setModel(new DefaultTableModel(null, new String[]{"Cod", "Item", "Valor", "Qtd."}));
        tabelaCaixa.setModel(new DefaultTableModel(null, new String[]{"Cod", "Item", "Valor", "Qtd."}));
        
        //Limpar campos pesquisados na tela de caixa e valores calculados
        limparCampos();
        limparValores();
        
        //Mudar para a tela de consulta
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_cancelarPagCaixaActionPerformed

    private void valorPagCaixaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valorPagCaixaFocusLost
        Float valorPago = Float.parseFloat(valorPagCaixa.getText());
        String valorTotal = (String.valueOf(Float.parseFloat(totalPagCaixa.getText())));
        Float troco = valorPago - Float.parseFloat(valorTotal);
        trocoCaixa.setText(troco.toString());
    }//GEN-LAST:event_valorPagCaixaFocusLost

    private void avancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avancarActionPerformed
        //Muda para a tela de caixa
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_avancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela04_B5_TabbedCaixaGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela04_B5_TabbedCaixaGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela04_B5_TabbedCaixaGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela04_B5_TabbedCaixaGerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela04_B5_TabbedCaixaGerencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarCaixa;
    private javax.swing.JButton avancar;
    private javax.swing.JButton btnLimparCaixa;
    private javax.swing.JButton btnPesquisarProd1;
    private javax.swing.JButton cancelarCaixa;
    private javax.swing.JButton cancelarPagCaixa;
    private javax.swing.JTextField codCaixa;
    private javax.swing.JButton creditoCaixa;
    private javax.swing.JButton debitoCaixa;
    private javax.swing.JButton dinheiroCaixa;
    private javax.swing.JButton excluirCaixa;
    private javax.swing.JButton finalizarCaixa;
    private javax.swing.JButton finalizarPagCaixa;
    private javax.swing.JTextField itemCaixa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField pesquisaProd1;
    private javax.swing.JTextField qtdCaixa;
    private javax.swing.JTable tabelaCaixa;
    private javax.swing.JTable tabelaPagCaixa;
    private javax.swing.JTable tabelaProdCaixa;
    private javax.swing.JTextField totalCaixa;
    private javax.swing.JTextField totalPagCaixa;
    private javax.swing.JTextField trocoCaixa;
    private javax.swing.JTextField valorCaixa;
    private javax.swing.JTextField valorPagCaixa;
    private javax.swing.JButton voltarCaixa;
    private javax.swing.JButton voltarPagamentoCaixa;
    private javax.swing.JButton voltarProdutosAtendimento;
    // End of variables declaration//GEN-END:variables
}
